Revert "Use `alignas()` in C++11"
This reverts commit eff96851ac4596a9e324813423b6df2c3a8b69b3.

This resulted in compile failures on MinGW:

    In file included from ../code/lib/glbuffer.cpp:14:
    ../contrib/xxHash/xxhash.h:983:4: error: 'alignas' attribute cannot be applied to types
       XXH_ALIGN_MEMBER(64, XXH64_hash_t acc[8]);
       ^
    ../contrib/xxHash/xxhash.h:937:47: note: expanded from macro 'XXH_ALIGN_MEMBER'
    #   define XXH_ALIGN_MEMBER(align, type) type XXH_ALIGN(align)
                                                  ^
    ../contrib/xxHash/xxhash.h:925:29: note: expanded from macro 'XXH_ALIGN'
    #  define XXH_ALIGN(n)      alignas(n)
                                ^
    ../contrib/xxHash/xxhash.h:985:4: error: 'alignas' attribute cannot be applied to types
       XXH_ALIGN_MEMBER(64, unsigned char customSecret[XXH3_SECRET_DEFAULT_SIZE]);
       ^
    ../contrib/xxHash/xxhash.h:937:47: note: expanded from macro 'XXH_ALIGN_MEMBER'
    #   define XXH_ALIGN_MEMBER(align, type) type XXH_ALIGN(align)
                                                  ^
    ../contrib/xxHash/xxhash.h:925:29: note: expanded from macro 'XXH_ALIGN'
    #  define XXH_ALIGN(n)      alignas(n)
                                ^
    ../contrib/xxHash/xxhash.h:987:4: error: 'alignas' attribute cannot be applied to types
       XXH_ALIGN_MEMBER(64, unsigned char buffer[XXH3_INTERNALBUFFER_SIZE]);
       ^
    ../contrib/xxHash/xxhash.h:937:47: note: expanded from macro 'XXH_ALIGN_MEMBER'
    #   define XXH_ALIGN_MEMBER(align, type) type XXH_ALIGN(align)
                                                  ^
    ../contrib/xxHash/xxhash.h:925:29: note: expanded from macro 'XXH_ALIGN'
    #  define XXH_ALIGN(n)      alignas(n)
                                ^
    3 errors generated.

Signed-off-by: Steven Noonan <steven@uplinklabs.net>